In [48]:
# setup
import io
import base64
import sys
import glob
import errno
from collections import defaultdict
import os
import gc

import numpy as np
import cupy as cp
import h5py
import scipy as sp
import pandas as pd
import itertools
import multiprocessing as mproc
import pandas as pd
import PIL as pil
import rembg
import glob
import calendar

sys.path.append(os.getcwd())

%reload_ext autoreload
%autoreload 2

from IPython.display import display, HTML, Math, Latex
display(HTML("<style>:root { --jp-notebook-max-width: 100% !important; }</style>"))

import matplotlib.pyplot as plt
# from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable
import matplotlib as mpl
# from mpl_toolkits.mplot3d import Axes3D

from jsd import jsd

%matplotlib inline
#%matplotlib notebook
    
# mpl.rcParams['text.usetex'] = 'True'
mpl.rcParams['axes.grid'] = False
mpl.rcParams['xtick.top'] = True
mpl.rcParams['xtick.bottom'] = True
mpl.rcParams['ytick.left'] = True
mpl.rcParams['ytick.right'] = True
mpl.rcParams['xtick.minor.visible'] = True
mpl.rcParams['ytick.minor.visible'] = True
mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['ytick.direction'] = 'in'
mpl.rcParams['xtick.major.size'] = 14
mpl.rcParams['ytick.major.size'] = 14
mpl.rcParams['xtick.minor.size'] = 7
mpl.rcParams['ytick.minor.size'] = 7
mpl.rcParams['xtick.major.width'] = 2
mpl.rcParams['ytick.major.width'] = 2
mpl.rcParams['xtick.minor.width'] = 1.2
mpl.rcParams['ytick.minor.width'] = 1.2
mpl.rcParams['axes.labelsize'] = 20
mpl.rcParams['xtick.labelsize'] = 20
mpl.rcParams['ytick.labelsize'] = 20
mpl.rcParams['legend.loc'] = 'best'
mpl.rcParams['legend.fontsize'] = 25
mpl.rcParams['lines.linewidth'] = 2
mpl.rcParams['pdf.fonttype'] = 42
mpl.rcParams['font.serif'] = 'Computer Modern'
mpl.rcParams['xtick.major.pad']='8'
mpl.rcParams['ytick.major.pad']='8'
mpl.rcParams['ytick.major.pad']='8'

blue = '#1f77b4'
orange = '#ff7f0e'
green = '#2ca02c'
red = '#ad494a'
violet = '#9467bd'
brown = '#8c564b'

In [49]:
db = jsd('data/All_crop.xlsx')
db_july = jsd(db.is_cultivation_time('July'))

In [46]:
db_july.is_crop('Tomato')

,Variety,Crop,Hybrid or OP,Sowing and transplant starting time,Sowing and transplant ending time,Best sowing and transplant starting time,Best sowing and transplant ending time,Maturity (days),After sowing or transplant,Weight (g),Fruit Size (cm),"Fruit shape, type, color",Disease Tolerance,Weather tolerance,Transport and storage property
9,F1 Hybrid Tomato Beautiful,Tomato,hybrid,January,December,January,December,50-55,transplant,150,,oval,"BW, Nematode, TYLCV",heat tolerant,good
10,F1 Hybrid Tomato Beautiful-2,Tomato,hybrid,January,December,January,December,65,transplant,135,7.2,oval,"BW, FW, TYLCV, LB",,good
15,F1 Hybrid Tomato Profit Early,Tomato,hybrid,May,August,May,August,50,transplant,135,,"oval, firm","BW, FW, TYLCV, TMV",heat tolerant,good
20,F1 Hybrid Tomato Super,Tomato,hybrid,July,October,July,October,55-66,transplant,150-200,,"oval , bright red, firm","BW, TMV",heat and rain tolerant,good

In [50]:
db.is_crop('Tomato')

,Variety,Crop,Hybrid or OP,Sowing and transplant starting time,Sowing and transplant ending time,Best sowing and transplant starting time,Best sowing and transplant ending time,Maturity (days),After sowing or transplant,Weight (g),Fruit Size (cm),"Fruit shape, type, color",Disease Tolerance,Weather tolerance,Transport and storage property
9,F1 Hybrid Tomato Beautiful,Tomato,hybrid,January,December,January,December,50-55,transplant,150,,oval,"BW, Nematode, TYLCV",heat tolerant,good
10,F1 Hybrid Tomato Beautiful-2,Tomato,hybrid,January,December,January,December,65,transplant,135,7.2,oval,"BW, FW, TYLCV, LB",,good
11,F1 Hybrid Tomato Sumo,Tomato,hybrid,November,November,November,November,70,transplant,200-250,,compact,Disease tolerant variety,,good
12,F1 Hybrid Tomato Wonderful Plus,Tomato,hybrid,August,November,August,November,70-75,transplant,140-150,,firm,"BW, FW, LB, TYLCV",,good
13,F1 Hybrid Tomato Ruposhi Plus,Tomato,hybrid,August,October,August,October,55-60,transplant,100-110,,firm,"BW, TYLCV",heat tolerant,good
14,F1 Hybrid Tomato Golden Cherry,Tomato,hybrid,August,October,August,October,50-55,transplant,30,,"compact, yellow","BW, TYLCV",,
15,F1 Hybrid Tomato Profit Early,Tomato,hybrid,May,August,May,August,50,transplant,135,,"oval, firm","BW, FW, TYLCV, TMV",heat tolerant,good
16,F1 Hybrid Tomato Red Cherry,Tomato,hybrid,August,October,August,October,45,transplant,20-22,,"firm, bright-red",,,good
17,F1 Hybrid Tomato Red King,Tomato,hybrid,April,June,April,June,60,transplant,100,6.1,"flattened-rounded, bright-red","BW, TYLCV",,
18,F1 Hybrid Tomato Lovely,Tomato,hybrid,August,October,August,October,50,transplant,130,,"firm, round","BW, Nematode, TYLCV",,good
19,F1 Hybrid Tomato Red Beauty-1,Tomato,hybrid,April,June,April,June,50-65,transplant,135,6.4,"flattened-rounded, red","BW, TYLCV",heat and rain tolerant,
20,F1 Hybrid Tomato Super,Tomato,hybrid,July,October,July,October,55-66,transplant,150-200,,"oval , bright red, firm","BW, TMV",heat and rain tolerant,good
21,F1 Hybrid Tomato Super Plus,Tomato,hybrid,August,November,August,November,65-70,transplant,110-130,,firm,"BW, FW, TYLCV",heat tolerant,good