In [ ]:
# setup
import io
import base64
import sys
import glob
import errno
from collections import defaultdict
import os
import gc

import numpy as np
import cupy as cp
import h5py
import scipy as sp
import pandas as pd
import itertools
import multiprocessing as mproc
import pandas as pd
import PIL as pil
import rembg
import glob
import calendar

sys.path.append(os.getcwd())

%reload_ext autoreload
%autoreload 2

from IPython.display import display, HTML, Math, Latex
display(HTML("<style>:root { --jp-notebook-max-width: 100% !important; }</style>"))

import matplotlib.pyplot as plt
# from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable
import matplotlib as mpl
# from mpl_toolkits.mplot3d import Axes3D

%matplotlib inline
#%matplotlib notebook
    
# mpl.rcParams['text.usetex'] = 'True'
mpl.rcParams['axes.grid'] = False
mpl.rcParams['xtick.top'] = True
mpl.rcParams['xtick.bottom'] = True
mpl.rcParams['ytick.left'] = True
mpl.rcParams['ytick.right'] = True
mpl.rcParams['xtick.minor.visible'] = True
mpl.rcParams['ytick.minor.visible'] = True
mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['ytick.direction'] = 'in'
mpl.rcParams['xtick.major.size'] = 14
mpl.rcParams['ytick.major.size'] = 14
mpl.rcParams['xtick.minor.size'] = 7
mpl.rcParams['ytick.minor.size'] = 7
mpl.rcParams['xtick.major.width'] = 2
mpl.rcParams['ytick.major.width'] = 2
mpl.rcParams['xtick.minor.width'] = 1.2
mpl.rcParams['ytick.minor.width'] = 1.2
mpl.rcParams['axes.labelsize'] = 20
mpl.rcParams['xtick.labelsize'] = 20
mpl.rcParams['ytick.labelsize'] = 20
mpl.rcParams['legend.loc'] = 'best'
mpl.rcParams['legend.fontsize'] = 25
mpl.rcParams['lines.linewidth'] = 2
mpl.rcParams['pdf.fonttype'] = 42
mpl.rcParams['font.serif'] = 'Computer Modern'
mpl.rcParams['xtick.major.pad']='8'
mpl.rcParams['ytick.major.pad']='8'
mpl.rcParams['ytick.major.pad']='8'

blue = '#1f77b4'
orange = '#ff7f0e'
green = '#2ca02c'
red = '#ad494a'
violet = '#9467bd'
brown = '#8c564b'

In [1]:
from jsd import jsd
db = jsd('data/All_crop.xlsx')

In [2]:
db.is_cultivation_time('July')
# db.is_crop('Tomato')

,Variety,Crop,Hybrid or OP,Sowing and transplant starting time,Sowing and transplant ending time,Best sowing and transplant starting time,Best sowing and transplant ending time,Maturity (days),After sowing or transplant,Weight (g),Fruit Size (cm),"Fruit shape, type, color",Disease Tolerance,Weather tolerance,Transport and storage property
0,F1 Hybrid Hot Pepper Hot Star,Hot Pepper,hybrid,January,December,January,December,50,transplant,13-15,11,"long, slim, red (ripe)",,heat,
1,F1 Hybrid Hot Pepper Balijuri,Hot Pepper,hybrid,January,December,January,December,50,transplant,7-9,10-12,glossy green to red,Yes,"heat, rain",
2,F1 Hybrid Hot Pepper Bengal Hot,Hot Pepper,hybrid,January,December,January,December,50-55,transplant,5,10,"glossy green, straight",,"heat, rain",
4,F1 Hybrid Hot Pepper Mohona,Hot Pepper,hybrid,January,December,January,December,50-55,transplant,10,13,green,,,
5,F1 Hybrid Hot Pepper Mohona-2,Hot Pepper,hybrid,January,December,December,February,50-55,transplant,8-10,10-12,green,Yes,,
6,F1 Hybrid Hot Pepper Siam Hot,Hot Pepper,hybrid,January,December,April,August,55-65,transplant,8-10,10-13,glossy green,Yes,"heat, rain",
7,F1 Hybrid Hot Pepper Thai Hot,Hot Pepper,hybrid,January,December,April,June,50,transplant,9-10,13,dark green,Yes,,
9,F1 Hybrid Tomato Beautiful,Tomato,hybrid,January,December,January,December,50-55,transplant,150,,oval,"BW, Nematode, TYLCV",heat tolerant,good
10,F1 Hybrid Tomato Beautiful-2,Tomato,hybrid,January,December,January,December,65,transplant,135,7.2,oval,"BW, FW, TYLCV, LB",,good
15,F1 Hybrid Tomato Profit Early,Tomato,hybrid,May,August,May,August,50,transplant,135,,"oval, firm","BW, FW, TYLCV, TMV",heat tolerant,good
20,F1 Hybrid Tomato Super,Tomato,hybrid,July,October,July,October,55-66,transplant,150-200,,"oval , bright red, firm","BW, TMV",heat and rain tolerant,good
23,F1 Hybrid Eggplant Long Black,Eggplant,hybrid,January,December,January,December,45-50,transplant,150-200,22,"cylinder, fat, glossy black purple",BW,,
24,F1 Hybrid Eggplant Green Super,Eggplant,hybrid,January,December,January,December,50-55,transplant,200-400,,"round to high round, green with strip",BW,,
25,F1 Hybrid Eggplant Rongdhonu,Eggplant,hybrid,January,December,January,December,50-55,transplant,200-500,8,"oval, glossy purple",BW,,
26,F1 Hybrid Eggplant Smart,Eggplant,hybrid,January,December,January,December,45-50,transplant,70-80,,"round oblong, glossy purple",BW,"heat, rain & long day length tolerant",
27,F1 Hybrid Eggplant Tasty,Eggplant,hybrid,January,December,January,December,55-60,transplant,250-600,8,"globe shape, purple-green",BW,,good
28,F1 Hybrid Cucumber All Rounder,Cucumber,hybrid,January,December,January,December,30-35,sowing,200-300,14,"green (summer), dark green (winter)",,,
29,F1 Hybrid Cucumber All Rounder-2,Cucumber,hybrid,January,December,January,December,35-40,sowing,200,13-15,green,virus and other disease tolerant,,
30,F1 Hybrid Cucumber Big Green,Cucumber,hybrid,January,December,December,April,35-45,sowing,400-500,30-35,"big, green",disease tolerant,dry season tolerant,
31,F1 Hybrid Cucumber Fantasy-1,Cucumber,hybrid,February,October,February,October,28-30,sowing,200,15,green,virus tolerant,"heat, rain tolerant",
32,F1 Hybrid Cucumber Fantasy-2,Cucumber,hybrid,February,October,February,October,28-30,sowing,200,14,green,virus tolerant,"heat, rain tolerant",
33,F1 Hybrid Cucumber Fortune-1,Cucumber,hybrid,March,September,March,September,35-40,sowing,200-250,17,green,virus tolerant,heat tolerant,
34,F1 Hybrid Cucumber Nice Green,Cucumber,hybrid,March,September,March,September,35,sowing,400-500,20,green,,"heat, rain tolerant",
35,F1 Hybrid Cucumber Shatabdi,Cucumber,hybrid,January,December,January,December,30-35,sowing,150-200,12,green,,,
36,F1 Hybrid Cucumber Shatabdi-2,Cucumber,hybrid,January,December,January,December,30-35,sowing,300,12,"oblong, green",downy mildew tolerant,,good
37,F1 Hybrid Cucumber Wonder Green,Cucumber,hybrid,January,December,December,April,35-45,sowing,400-500,24-25,"green (hot season), dark green (winter)","downy mildew, virus tolerant",,
38,F1 Hybrid Cucumber Fantasy Green,Cucumber,hybrid,February,October,February,October,30-35,sowing,180-200,2026-12-14 00:00:00,green,virus tolerant,"heat, rain tolerant",
39,F1 Hybrid Cucumber Gentleman,Cucumber,hybrid,February,October,February,October,40-45,sowing,180,15-18,green,"downy mildew, virus tolerant","heat, rain tolerant",

In [3]:
db.dataframe

,Variety,Crop,Hybrid or OP,Sowing and transplant starting time,Sowing and transplant ending time,Best sowing and transplant starting time,Best sowing and transplant ending time,Maturity (days),After sowing or transplant,Weight (g),Fruit Size (cm),"Fruit shape, type, color",Disease Tolerance,Weather tolerance,Transport and storage property
0,F1 Hybrid Hot Pepper Hot Star,Hot Pepper,hybrid,January,December,January,December,50,transplant,13-15,11,"long, slim, red (ripe)",,heat,
1,F1 Hybrid Hot Pepper Balijuri,Hot Pepper,hybrid,January,December,January,December,50,transplant,7-9,10-12,glossy green to red,Yes,"heat, rain",
2,F1 Hybrid Hot Pepper Bengal Hot,Hot Pepper,hybrid,January,December,January,December,50-55,transplant,5,10,"glossy green, straight",,"heat, rain",
3,F1 Hybrid Hot Pepper Bindhu,Hot Pepper,hybrid,December,February,December,February,50,transplant,3-4,7-8,glossy green,,,
4,F1 Hybrid Hot Pepper Mohona,Hot Pepper,hybrid,January,December,January,December,50-55,transplant,10,13,green,,,
5,F1 Hybrid Hot Pepper Mohona-2,Hot Pepper,hybrid,January,December,December,February,50-55,transplant,8-10,10-12,green,Yes,,
6,F1 Hybrid Hot Pepper Siam Hot,Hot Pepper,hybrid,January,December,April,August,55-65,transplant,8-10,10-13,glossy green,Yes,"heat, rain",
7,F1 Hybrid Hot Pepper Thai Hot,Hot Pepper,hybrid,January,December,April,June,50,transplant,9-10,13,dark green,Yes,,
8,F1 Hybrid Capsicum Green Bell,Capsicum,hybrid,December,February,December,February,65,transplant,200,10,"bell shape, green",,heat,
9,F1 Hybrid Tomato Beautiful,Tomato,hybrid,January,December,January,December,50-55,transplant,150,,oval,"BW, Nematode, TYLCV",heat tolerant,good
10,F1 Hybrid Tomato Beautiful-2,Tomato,hybrid,January,December,January,December,65,transplant,135,7.2,oval,"BW, FW, TYLCV, LB",,good
11,F1 Hybrid Tomato Sumo,Tomato,hybrid,November,November,November,November,70,transplant,200-250,,compact,Disease tolerant variety,,good
12,F1 Hybrid Tomato Wonderful Plus,Tomato,hybrid,August,November,August,November,70-75,transplant,140-150,,firm,"BW, FW, LB, TYLCV",,good
13,F1 Hybrid Tomato Ruposhi Plus,Tomato,hybrid,August,October,August,October,55-60,transplant,100-110,,firm,"BW, TYLCV",heat tolerant,good
14,F1 Hybrid Tomato Golden Cherry,Tomato,hybrid,August,October,August,October,50-55,transplant,30,,"compact, yellow","BW, TYLCV",,
15,F1 Hybrid Tomato Profit Early,Tomato,hybrid,May,August,May,August,50,transplant,135,,"oval, firm","BW, FW, TYLCV, TMV",heat tolerant,good
16,F1 Hybrid Tomato Red Cherry,Tomato,hybrid,August,October,August,October,45,transplant,20-22,,"firm, bright-red",,,good
17,F1 Hybrid Tomato Red King,Tomato,hybrid,April,June,April,June,60,transplant,100,6.1,"flattened-rounded, bright-red","BW, TYLCV",,
18,F1 Hybrid Tomato Lovely,Tomato,hybrid,August,October,August,October,50,transplant,130,,"firm, round","BW, Nematode, TYLCV",,good
19,F1 Hybrid Tomato Red Beauty-1,Tomato,hybrid,April,June,April,June,50-65,transplant,135,6.4,"flattened-rounded, red","BW, TYLCV",heat and rain tolerant,
20,F1 Hybrid Tomato Super,Tomato,hybrid,July,October,July,October,55-66,transplant,150-200,,"oval , bright red, firm","BW, TMV",heat and rain tolerant,good
21,F1 Hybrid Tomato Super Plus,Tomato,hybrid,August,November,August,November,65-70,transplant,110-130,,firm,"BW, FW, TYLCV",heat tolerant,good
22,F1 Hybrid Eggplant Chomok,Eggplant,hybrid,January,January,July,October,50,transplant,200,22,"cylinder, fat, deep purple",,,
23,F1 Hybrid Eggplant Long Black,Eggplant,hybrid,January,December,January,December,45-50,transplant,150-200,22,"cylinder, fat, glossy black purple",BW,,
24,F1 Hybrid Eggplant Green Super,Eggplant,hybrid,January,December,January,December,50-55,transplant,200-400,,"round to high round, green with strip",BW,,
25,F1 Hybrid Eggplant Rongdhonu,Eggplant,hybrid,January,December,January,December,50-55,transplant,200-500,8,"oval, glossy purple",BW,,
26,F1 Hybrid Eggplant Smart,Eggplant,hybrid,January,December,January,December,45-50,transplant,70-80,,"round oblong, glossy purple",BW,"heat, rain & long day length tolerant",
27,F1 Hybrid Eggplant Tasty,Eggplant,hybrid,January,December,January,December,55-60,transplant,250-600,8,"globe shape, purple-green",BW,,good
28,F1 Hybrid Cucumber All Rounder,Cucumber,hybrid,January,December,January,December,30-35,sowing,200-300,14,"green (summer), dark green (winter)",,,
29,F1 Hybrid Cucumber All Rounder-2,Cucumber,hybrid,January,December,January,December,35-40,sowing,200,13-15,green,virus and other disease tolerant,,
30,F1 Hybrid Cucumber Big Green,Cucumber,hybrid,January,December,December,April,35-45,sowing,400-500,30-35,"big, green",disease tolerant,dry season tolerant,
31,F1 Hybrid Cucumber Fantasy-1,Cucumber,hybrid,February,October,February,October,28-30,sowing,200,15,green,virus tolerant,"heat, rain tolerant",
32,F1 Hybrid Cucumber Fantasy-2,Cucumber,hybrid,February,October,February,October,28-30,sowing,200,14,green,virus tolerant,"heat, rain tolerant",
33,F1 Hybrid Cucumber Fortune-1,Cucumber,hybrid,March,September,March,September,35-40,sowing,200-250,17,green,virus tolerant,heat tolerant,
34,F1 Hybrid Cucumber Nice Green,Cucumber,hybrid,March,September,March,September,35,sowing,400-500,20,green,,"heat, rain tolerant",
35,F1 Hybrid Cucumber Shatabdi,Cucumber,hybrid,January,December,January,December,30-35,sowing,150-200,12,green,,,
36,F1 Hybrid Cucumber Shatabdi-2,Cucumber,hybrid,January,December,January,December,30-35,sowing,300,12,"oblong, green",downy mildew tolerant,,good
37,F1 Hybrid Cucumber Wonder Green,Cucumber,hybrid,January,December,December,April,35-45,sowing,400-500,24-25,"green (hot season), dark green (winter)","downy mildew, virus tolerant",,
38,F1 Hybrid Cucumber Fantasy Green,Cucumber,hybrid,February,October,February,October,30-35,sowing,180-200,2026-12-14 00:00:00,green,virus tolerant,"heat, rain tolerant",
39,F1 Hybrid Cucumber Gentleman,Cucumber,hybrid,February,October,February,October,40-45,sowing,180,15-18,green,"downy mildew, virus tolerant","heat, rain tolerant",